### ISSUE TITLE
Server crahs when Y for ores is too high

### ISSUE THREAD

**Issue by wireva** [sfan5/we_env#6] opened 2019-04-27 17:25 UTC
debug.txt:
from debug.txt:
`2019-04-27 19:06:50: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'we_env' in callback on_chat_message(): Invalid float vector dimension range 'y' (expected -2.14748e+006 < y < 2.14748e+006 got 5e+007).
2019-04-27 19:06:50: ERROR[Main]: stack traceback:
2019-04-27 19:06:50: ERROR[Main]: 	[C]: in function 'VoxelManip'
2019-04-27 19:06:50: ERROR[Main]: 	...inetest\minetest-5.0.0-win64\bin\..\mods\we_env\init.lua:135: in function 'ores'
2019-04-27 19:06:50: ERROR[Main]: 	...inetest\minetest-5.0.0-win64\bin\..\mods\we_env\init.lua:400: in function 'func'
2019-04-27 19:06:50: ERROR[Main]: 	...inetest-5.0.0-win64\bin\..\builtin\game\chatcommands.lua:30: in function <...inetest-5.0.0-win64\bin\..\builtin\game\chatcommands.lua:9>
2019-04-27 19:06:50: ERROR[Main]: 	...st\minetest-5.0.0-win64\bin\..\builtin\game\register.lua:419: in function <...st\minetest-5.0.0-win64\bin\..\builtin\game\register.lua:399>
2019-04-27 19:06:50: ACTION[Server]: Niwla leaves game. List of players: 
2019-04-27 19:06:50: ACTION[Main]: Server: Shutting down`

**Comment by sfan5** [comment] 2019-04-27 17:27
duplicate of #5

**Comment by wireva** [comment] 2019-04-27 17:28
no, i changed iteration to y please reopen it

**Comment by wireva** [comment] 2019-04-27 17:28
@sfan5

**Closed as completed by sfan5** 2019-04-27 17:27 UTC
